FROM nginx:stable

RUN mkdir -p /var/www/html /etc/nginx/ssl
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY conf/nginx.crt /etc/nginx/ssl/nginx.crt
COPY conf/nginx.key /etc/nginx/ssl/nginx.key
RUN chmod 644 /etc/nginx/ssl/nginx.crt && chmod 600 /etc/nginx/ssl/nginx.key

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
